name: Tests GHA

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.12]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Requirements
        run: |
          python -m pip install --upgrade pip
          pip install -r airflow/requirements.txt  # Use this if you have a requirements file
          
      - name: Tests
        run: |
          for test_file in $(find .airflow/tests -name "*.py"); do
            echo "Running $test_file"
            python $test_file
          done